disxss/frontends/views.py
# -*- coding: utf-8 -*-
"""
"""

import flask
from flask import (Blueprint, request, render_template, flash,
    g, session, redirect, url_for, jsonify, abort)

from werkzeug import check_password_hash, generate_password_hash
import datetime
from easydict import EasyDict as edict
from bson import json_util, ObjectId
import pymongo
from umongo import ValidationError

# from disxss import db
from disxss.users.forms import RegisterForm, LoginForm
from disxss.users.models import User
from disxss.users.decorators import requires_login
from disxss import app
from disxss.threads.models import Thread
from disxss.categories.models import Category
from disxss import search_utils # don't override function name

from disxss import db
from disxss import db_utils


bp = Blueprint('frontends', __name__, url_prefix='')

@bp.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        app.logger.debug({'id': session['user_id']})
        g.user = User.find({'id': ObjectId(session['user_id'])})[0]
        # g.user = User.query.get(session['user_id'])
        # g.user = User(document=users.find_one_or_404({'_id': ObjectId(session['user_id'])}))

def home_category():

    #TODO: convert to mongodb
    # return Category.query.get_or_404(1)

    s = Category.find_one({})
    if s is None:
        # abort(404)
        flash("There are no categories yet, create one!")
    return s

def get_categories():
    """
    important and widely imported method because a list of
    the top 30 categories are present on every page in the sidebar
    """

    # TODO:
    # convert to mongodb
    # categories = []
    # categories = Category.query.filter(Category.id != 1)[:25]
    categories = Category.find({"id": {"$ne": 1}})[:25]
    app.logger.debug("in frontends.views: categories: {}".format(categories))
    return categories

def process_thread_paginator(trending=False, rs=None, category=None):
    """
    abstracted because many sources pull from a thread listing
    source (category permalink, homepage, etc)
    """
    threads_per_page = 15
    cur_page = request.args.get('page') or 1
    cur_page = int(cur_page)
    thread_paginator = None

    # if we are passing in a resultset, that means we are just looking to
    # quickly paginate some arbitrary data, no sorting
    if rs is not None:
        # thread_paginator = rs.paginate(cur_page, per_page=threads_per_page,
        #     error_out=True)
        app.logger.debug(rs)
        thread_paginator=db_utils.paginate(rs, page_num=cur_page, page_size=threads_per_page)
        return thread_paginator

    # sexy line of code :)
    app.logger.debug("category: {}".format(category))
    if category is not None:
        app.logger.debug("category.threads: {}".format(category.get_threads()))
    app.logger.debug("Thread: {}".format(Thread.find()))
    def get_base_query():
        if category is not None and category.get_threads() is not None:
            app.logger.debug("category.threads: {}".format(category.get_threads()))
            return category.get_threads()
        else:
            return Thread.find()


    base_query = get_base_query()
    app.logger.debug("base_query: {}".format(base_query))
    app.logger.debug("base_query: {}".format([x for x in base_query]))
    base_query = get_base_query()
    if trending:
        thread_paginator = base_query.sort([("num_votes", pymongo.DESCENDING)])
        thread_paginator = db_utils.paginate(thread_paginator,
            page_num=cur_page, page_size=threads_per_page)
        app.logger.debug("thread_paginator: {}".format(thread_paginator[:]))
    else:
        thread_paginator = base_query.sort([("hotness", pymongo.DESCENDING)])
        thread_paginator = db_utils.paginate(thread_paginator, page_num=cur_page, page_size=threads_per_page)
    return thread_paginator

# @bp.route('/<regex("trending"):trending>/')
@bp.route('/')
def home(trending=False):
    """
    If not trending we order by creation date
    """
    trending = True if request.args.get('trending') else trending
    categories = get_categories()
    app.logger.debug("categories: {}".format([x for x in categories]))

    #---------------------------------------------------------------------
    # TODO: fix pagination
    thread_paginator = process_thread_paginator(trending=trending)
    app.logger.debug("thread_paginator: {}".format(thread_paginator))
    # thread_paginator = []
    #---------------------------------------------------------------------


    return render_template('home.html', user=g.user,
            categories=categories,
            cur_category=home_category(),
            thread_paginator=thread_paginator)

@bp.route('/search/', methods=['GET'])
def search():
    """
    Allows users to search threads and comments
    """
    query = request.args.get('query')
    rs = search_utils.search(query, orderby='date_created', search_title=True,
            search_text=True, limit=100)

    thread_paginator = process_thread_paginator(rs=rs)

    num_searches = 0
    app.logger.debug("rs: {}".format(rs))
    if rs:
        num_searches = rs.count()

    categories = get_categories()

    return render_template('home.html', user=g.user,
            categories=categories, cur_category=home_category(),
            thread_paginator=thread_paginator, num_searches=num_searches)

@bp.route('/login/', methods=['GET', 'POST'])
def login():
    """
    We had to do some extra work to route the user back to
    his or her original place before logging in
    """
    if g.user:
        return redirect(url_for('frontends.home'))

    next = ''
    if request.method == 'GET':
        if 'next' in request.args:
            next = request.args['next']

    form = LoginForm(request.form)
    # make sure data is valid, but doesn't validate password is right
    if form.validate_on_submit():
        # continue where we left off if so
        # user = User.query.filter_by(email=form.email.data).first()

        # app.logger.debug(db.users.find({'email': form.email.data})[0])
        app.logger.debug({'email': form.email.data})

        app.logger.debug(User.find({'email': form.email.data}))
        user = User.find({'email': form.email.data})[0]
        app.logger.debug("user: {user}".format(user=user))
        app.logger.debug("finding email: {}".format(form.email.data))
        app.logger.debug("user found: {}".format((user.email, user.username)))
        # user = edict(user)

        # user = User(document=document)

        # we use werzeug to validate user's password
        if user and check_password_hash(user.password, form.password.data):
            # the session can't be modified as it's signed,
            # it's a safe place to store the user id
            app.logger.debug("user: {}".format(user.username))

            session['user_id'] = str(user.id)

            if 'next' in request.form and request.form['next']:
                return redirect(request.form['next'])

            flash('You are logged in', 'success')
            return redirect(url_for('frontends.home'))

        elif not user:
            flash("You haven't signed up, please register", 'danger')
            return redirect(url_for('frontends.register'))
        else:
            flash('Wrong email or password', 'danger')
    return render_template("login.html", form=form, next=next)

@bp.route('/logout/', methods=['GET', 'POST'])
@requires_login
def logout():
    session.pop('user_id', None)
    app.logger.debug("logging out")
    return redirect(url_for('frontends.home'))

@bp.route('/register/', methods=['GET', 'POST'])
def register():
    """
    """

    app.logger.debug("request.args: {}".format(request.args))
    next = ''
    if request.method == 'GET':
        if 'next' in request.args:
            next = request.args['next']

    form = RegisterForm(request.form)
    app.logger.debug("form: {}"
        .format("\n".join("-- form -- {}: {}".format(k,v) for k,v in form.__dict__.items())))


    app.logger.debug("is submitted: {}".format(form.is_submitted()))
    app.logger.debug("is validated: {}".format(form.validate()))

    if form.validate_on_submit():
        # create an user instance not yet stored in the database
        created_at = datetime.datetime.now()
        modified_at = datetime.datetime.now()

        app.logger.debug("username : {}".format(form.username))
        app.logger.debug("password : {}".format(form._fields['password'].data))
        app.logger.debug("password : {}".format(form.password.data))
        app.logger.debug("username : {}".format(form.username.data))

        app.logger.debug("username : {}".format(generate_password_hash(form.password.data)))

        # user = User(username=form.username.data, email=form.email.data,
        #         password=generate_password_hash(form.password.data),
        #         # created_at=created_at,
        #         # modified_at=modified_at
        #         )

        password = generate_password_hash(form.password.data)
        # user = User(username=form.username.data,
        #             email=form.email.data,
        #         password=password,
        #         created_at=created_at,
        #         modified_at=modified_at
        #         ).save()

        data = {'username':form.username.data,
                'email':form.email.data,
                'password':password,
                # 'created_at':created_at,
                # 'modified_at':modified_at
                }

        # user = User(**userdoc).save()
        # User.ensure_indexes()

        try:
            user = User(**data)
            user.commit()
        except ValidationError as e:
            app.logger.error(str(e))
            flash(str(e), 'danger')
            return redirect(url_for('frontends.register'))

        # User(**data).commit()
        # user = User.find_one({'email': data['email']})

        # user_id = db.users.insert_one(post).inserted_id

disxss/threads/views.py
# -*- coding: utf-8 -*-
"""
"""


from bson.objectid import ObjectId

from flask import (Blueprint, request, render_template, flash, g, session,
    redirect, url_for, abort)


from disxss.threads.forms import SubmitForm
from disxss.threads.models import Thread
from disxss.users.models import User
from disxss.categories.models import Category
from disxss.frontends.views import get_categories
from disxss import db
from disxss import app

bp = Blueprint('threads', __name__, url_prefix='/threads')

# Threads Views #

@bp.before_request
def before_request():
    g.user = None
    if 'user_id' in session:
        g.user = User.find({'id': ObjectId(session['user_id'])})[0]
        app.logger.debug("filter user : {}".format(session['user_id']))


def meets_thread_criteria(thread):
    """
    """
    app.logger.debug("thread: {}".format(thread))
    if not thread.title:
        flash('You must include a title!', 'danger')
        return False
    if not thread.text and not thread.link:
        flash('You must post either body text or a link!', 'danger')
        return False

    dup_link = Thread.find_one({"link":thread.link})
    app.logger.debug("duplicate link: {}".format(dup_link))
    if not thread.text or dup_link:
        flash('someone has already posted the same link as you!', 'danger')
        return False

    return True

@bp.route('/<category_name>/submit/', methods=['GET', 'POST'])
def submit(category_name=None):
    """
    """
    if g.user is None:
        flash('You must be logged in to submit posts!', 'danger')
        return redirect(url_for('frontends.login', next=request.path))
    user_id = g.user.id


    categories = Category.find({"name":category_name})
    category = None
    if categories.count() > 0:
        category = categories[0]
    if not category:
        flash('Select a category!', 'danger')
        # abort(404)
        return redirect(url_for('frontends.home', next=request.path))


    form = SubmitForm(request.form)
    if form.validate_on_submit():
        title = form.title.data.strip()
        link = form.link.data.strip()
        text = form.text.data.strip()

        thread_data = {"title":title, "link":link, "text":text,
                "user_id":user_id, "category_id":category.id,
                "user": g.user,
                "category": category}
        thread = Thread(**thread_data)

        if not meets_thread_criteria(thread):
            return render_template('threads/submit.html', form=form, user=g.user,
                cur_category=category.name)

        thread.update()
        thread.commit()
        app.logger.debug("adding thread: category name: {}"
                         .format(thread.category))
        app.logger.debug("adding thread: category name: {}"
                         .format(thread.category.fetch().name))
        # db.threads.add_thread
        # db.session.add(thread)
        # db.session.commit()

        # thread.set_hotness()
        # thread.add_thread()

        flash('thanks for submitting!', 'success')
        return redirect(url_for('categories.permalink', category_name=category.name))
    return render_template('threads/submit.html', form=form, user=g.user,
            cur_category=category, categories=get_categories())

@bp.route('/delete/', methods=['GET', 'POST'])
def delete():
    """
    """
    pass

@bp.route('/edit/', methods=['GET', 'POST'])
def edit():
    """
    """
    pass

@bp.route('/<category_name>/<thread_id>/<path:title>/', methods=['GET', 'POST'])
def thread_permalink(category_name=None, thread_id=None, title=None):
    """
    """
    thread_id = thread_id #or -99
    app.logger.debug("thread_id: {}".format(thread_id))
    thread = Thread.find_one({"id": ObjectId(thread_id)})

    app.logger.debug(Category.find({"name":category_name}))
    category = Category.find_one({"name":category_name})
    categories = get_categories()
    return render_template('threads/permalink.html', user=g.user, thread=thread,
            cur_category=category, categories=categories)


##########################
##### Comments Views #####
##########################

@bp.route('/comments/submit/', methods=['GET', 'POST'])
def submit_comment():
    """
    """
    pass

@bp.route('/comments/delete/', methods=['GET', 'POST'])
def delete_comment():
    """
    """
    pass

@bp.route('/comments/<comment_id>/', methods=['GET', 'POST'])
def comment_permalink():
    """
    """
    pass

disxss/users/views.py
# -*- coding: utf-8 -*-
"""
"""
from flask import (Blueprint, request, render_template, flash, g, session,
    redirect, url_for, abort, jsonify)
from bson import ObjectId

# TODO: frontends, db imports
# # from flask_reddit import db
from disxss.frontends.views import get_categories

from disxss.users.models import User, dump_user_no_pass
from disxss.threads.models import Thread
from disxss.users.decorators import requires_login
from disxss import app
from disxss import db

bp = Blueprint('users', __name__, url_prefix='/users')

@bp.before_request
def before_request():
    g.user = None

    if 'user_id' in session:
        g.user = db.users.find({'_id': ObjectId(session['user_id'])})[0]
        app.logger.debug("filter user : {}".format(session['user_id']))


@bp.route('/<username>/')
def home_page(username=None):
    if not username:
        abort(404)

    # TODO: port to mongodb query
    # user = User.query.filter_by(username=username).first()
    cursor = User.find({'username': username})
    user = cursor[0]
    # user['thread_karma'] = Thread.find({"user_id":user.id})
    app.logger.debug("user cursor: {}".format(cursor))
    app.logger.debug("user dict: {}".format(user))
    app.logger.debug("thread karma: {}".format(user.get_thread_karma()))
    # user = db.users.find_one_or_404({"username": username})

    # threads = Thread.find({'user_id': user.id})
    if not user:
        abort(404)
    return render_template('users/profile.html',
            user=user, current_user=user,
            categories = get_categories(),
            )



@app.route('/users', methods=['GET'])
def list_users():
    page = int(request.args.get('page', 1))
    users = User.find().limit(10).skip((page - 1) * 10)
    return jsonify({
        '_total': users.count(),
        '_page': page,
        '_per_page': 10,
        '_items': [dump_user_no_pass(u) for u in users]
    })

disxss/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <!--<meta name="viewport" content="width=device-width, initial-scale=1.0">-->
    <meta name="description" content="An extendable Reddit clone built with flask by
         Lucas Ou-Yang.">
    <meta name="author" content="Lucas Ou-Yang">
    <title>{% block title %}Reddit clone built with flask, python, nginx, etc{% endblock %}</title>
    <meta name="keywords" content="flask,reddit,python,reddit-clone,nginx,lucas ou-yang">

    <!-- Bootstrap core CSS -->
    <!-- <link href="css/bootstrap.css" rel="stylesheet"> -->
    <link rel="icon" href="https://reddit.codelucas.com/static/imgs/favicon.ico" type="image/x-icon">
    {% block css %}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    {% endblock %}

    <!-- Add custom CSS here -->
    <style>
        body {margin-top: 60px;}
    </style>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
              <li>
                  <a class="brand-nav" href="/">
                      {% if cur_category is defined and cur_category.id != 1 %}
                          {{ cur_category.name }}
                      {% else %}
                          {{ config.BRAND }}
                      {% endif %}
                  </a>
              </li>
              <li>
                  <a href="/?trending=true">trending</a>
              </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          {% if user is not defined or user == None %}
              <li><a href="{{ url_for('frontends.register', next=request.path) }}">Register</a></li>
              <li><a href="{{ url_for('frontends.login', next=request.path) }}">Login</a></li>
          {% else %}
              <p class="navbar-text login-nav-text">logged in as
                  <a href="{{ url_for('users.home_page', username=user.username) }}">
                      {{ user.username }}</a>, &nbsp;
                  {{ user.get_thread_karma() }} <span class="karma-star">★</span>
              </p>
              <li class="logout-button">
                  {#
                      <!-- <a href="{{ config.ROOT_URL }}/logout">logout</a> -->
                   #}
                  <a href="{{ url_for('frontends.logout', next=request.path) }}">logout</a>
              </li>
          {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav>

    <div class="container">
      <div id="messages-wrap">
        <div id="messages">
          {% for category, msg in get_flashed_messages(with_categories=true) %}
          <div class="flash-{{ category }} alert alert-dismissable alert-{{ category }} flash-banner">
              {{ msg }}</p>
          {% endfor %}
        </div>
      </div>

      <div class="row main-box">
      {% block content %}

      {% endblock %}
      </div>

      <div class="row" class="" id="footer-row">
          <div class="col-lg-12">
          </div>
      </div>

    </div><!-- /.container -->

    <!-- JavaScript -->
    <!-- TODO Fix this -->
    <!-- <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-37131973-4', 'codelucas.com');
      ga('send', 'pageview');
    </script> -->

    <!-- Let's use a CDN -->

    {# NOTE: MathJax self-hosted cdn retired, use alternate hosts as
             explained here: https://www.mathjax.org/cdn-shutting-down/
    #}
    <!-- <script  src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script> -->
    <!-- <script type="text/javascript" async
      src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?...">
    </script> -->
    <script
      src="https://cdn.rawgit.com/mathjax/MathJax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    </script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    {% block scripts %}


    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
          TeX: {
             equationNumbers: {  autoNumber: "AMS"  },
             extensions: ["AMSmath.js", "AMSsymbols.js", "autobold.js", "color.js"]
          }
        });
    </script>

    {% endblock %}
  </body>
</html>

disxss/templates/csrf_error.html
{% extends "base.html" %}

{% block content %}
<div class="col-lg-9">
  <h1>400</h1>
  <p class="lead">CSRFError!</p>
</div>
{% endblock %}

disxss/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="col-lg-9 col-md-9 col-sm-7 col-xs-5 left-bar">
  {% block left %}
      {% if num_searches is defined %}
        <h4 class="highlight">We have found {{ num_searches }} search results </h4>
        <br>
      {% endif %}
      <div class="spacer"></div>

      {% for thread in thread_paginator %}
        <div name="{{ thread.id }}" class="row listing-row">
          <div class="col-lg-1 listing-vote-box">
              <div class="">
                  {% if user is defined and user != None and thread.has_voted(user.id) %}
                      <a data-voted="true" style="color:#eb6864;" href="javascript:void(0)"
                          class="listing-vote-button" id="thread-vote">▲</a>
                  {% else %}
                      <a data-voted="false" style="color:#000;" href="javascript:void(0)"
                          class="listing-vote-button" id="thread-vote">▲</a>
                  {% endif %}
              </div>
              <div class="listing-votes-number">
                  {{ thread.num_votes }}
              </div>
          </div>
          <div class="col-lg-1 listing-thumbnail-box">
              <img class="listing-image" src="{{ thread.thumbnail|replace("http://", "https://") }}"/>
          </div>
          <div class="col-lg-8 listing-text">
              {% if thread.link %}
                    <a href="{{ thread.link }}" class="listing-title">
              {% else %}
                    <a href="{{ url_for('threads.thread_permalink',
                                  category_name=thread.category.fetch().name,
                                  thread_id=thread.id,
                                  title=thread.title) }}">
                       {# href="{{ config.ROOT_URL }}/threads/{{ thread.category.fetch().name }}/{{ thread.id }}/{{ thread.title|truncate(100)|replace(' ', '_') }}/" class="listing-title"> #}
              {% endif %}
                <h4 class="listing-title-text">{{ thread.title }}</h4>
              </a>

              <div class="post-listing-meta">
                  <a href="{{ url_for('threads.thread_permalink',
                                category_name=thread.category.fetch().name,
                                thread_id=thread.id,
                                title=thread.title) }}">
                      <!-- {# href="{{ config.ROOT_URL }}/threads/{{ thread.category.fetch().name }}/{{ thread.id }}/{{ thread.title|truncate(100)|replace(' ', '_') }}/" > #} -->
                      {#<!-- {{ thread.comments()|length() }} comments -->#}

                      {{ thread.get_comment_count() }} comments
                  </a>,
                  {{ thread.pretty_date() }}, by
                  <a href="{{ url_for('users.home_page',
                        username=thread.user.fetch().username) }}">
                        {{ thread.user.fetch().username }}</a>
                    in
                    <a href="{{ url_for('categories.permalink',
                        category_name=thread.category.fetch().name) }}">
                        {{ thread.category.fetch().name }}
                    </a>
              </div>
          </div>
        </div>
      {% endfor %}

      <ul class="pager pull-left">
        {% if thread_paginator.has_prev %}
            <li><a href="?page={{ thread_paginator.prev_num }}">prev</a></li>
        {% else %}
            <li style="opacity:0.3;"><a>prev</a></li>
        {% endif %}
        {% if thread_paginator.has_next %}
            <li><a href="?page={{ thread_paginator.next_num }}">next</a></li>
        {% else %}
            <li style="opacity:0.3;"><a>next</a></li>
        {% endif %}
      </ul>


  {% endblock %}
</div>

<div class="col-lg-3 right-bar">
  {% block right %}
    {% if user is defined and user != None %}
        <!-- -->
    {% else %}
        <h4 class="pre-reg-info">Please register or login to post!</h4>
    {% endif %}
    {% block create_buttons %}



    {# TODO: disable after adding threads #}


    <div class="row">
        {% block user_dashboard %}
        {% endblock %}
        <form method="GET" action="/search/" class="" role="search">
            <div class="form-group">
                <input type="text" name="query" class="reddit-search form-control"
                    placeholder="Search reddit!">
            </div>

                {#TODO keep commented in html #}
                <button type="submit" class="btn btn-default">Submit</button>


        </form>

        {% if cur_category is defined and cur_category != None %}
            <a href="{{ url_for('threads.submit', category_name=cur_category.name) }}">
                <button class="btn btn-primary submit-post-button">
                    submit to {{ cur_category.name }}</button>
            </a>
        {% else %}
            <a href="{{ url_for('threads.submit', category_name='frontpage') }}">
                <button class="btn btn-primary submit-post-button">submit post</button></a>
        {% endif %}
    </div>

    <div class="row">
        <a href="{{ url_for('categories.submit') }}">
            <button type="button" class="btn btn-primary
        inverse-white-button add-category-button">create community +</button></a>
    </div>

    {% if cur_category is defined %}
    <p class="category-desc">
        {{ cur_category.desc }}
    </p>
    {% endif %}



    {% endblock %}



    <h4 class="category-desc">Categories</h4>
    <ul id="category-list">
        {% for category in categories %}
        <li><a href="/r/{{ category.name }}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
    <a class="align-right-col" href="{{ url_for('categories.view_all') }}">view all</a>
    <i>
    <div class="align-right-col byline-lucas">Built by:
        <a href="https://disxss.com">Free Throw </a>.
        <br>
        <a href="https://github.com/codelucas/flask_reddit">
            View code on Github</a>.</div>
    </i>


  {% endblock %}


</div>

{% endblock %}

{% block scripts %}
<script type="text/javascript">

// Inject CSRF Token
// Some referencens
// ref1: https://blog.miguelgrinberg.com/post/cookie-security-for-flask-applications
// ref2: https://medium.com/@doobeh/posting-a-wtform-via-ajax-with-flask-b977782edeee
var csrf_token = "{{ csrf_token() }}";  // the token is set by Jinja2
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrf_token);  // insert custom header
        }
    }
});

$(document).ready(function() {
    $(document).on('click', '#thread-vote', function() {
        var $vote_button = $(this); // cache this! can't access in callback!
        var thread_id = $vote_button.parent().parent().parent().attr('name');
        var post_to = '/apis/threads/vote/';
        if ($vote_button.attr("data-voted") === "true") {
            $vote_button.css("color", "#000");
            $vote_button.attr("data-voted", "false");
        } else {
            $vote_button.css("color", "rgb(235, 104, 100)");
            $vote_button.attr("data-voted", "true");
        }
        {% if user is defined and user != None %}
            $.post(post_to, { thread_id: thread_id },
                function(response) {
                    var new_vote_count = response.new_votes.toString();
                    var vote_status = response.vote_status;
                    $vote_button.parent().parent().
                        children('div.listing-votes-number').html(new_vote_count);
                }, 'json'
            );
        {% else %}
            alert("You must be logged in to do that!");
        {% endif %}
    });
    //
    //
});
</script>
{% endblock %}

disxss/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-md-offset-4">
            <h1 class="text-center login-title">Sign in to continue to Disxss</h1>
            <div class="account-wall">
                <img class="profile-img" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=120"
                    alt="">
                {% from "macros.html" import render_field %}
                <form method="POST" action="." class="form-signin">
                {{ form.csrf_token }}
                <input type="hidden" name="next" value="{{ next }}"/>
                {{ render_field(form.email, class="form-control",
                    placeholder="Email", autofocus="") }}
                {{ render_field(form.password, class="form-control", placeholder="Password") }}
                <button class="btn btn-lg btn-primary btn-block" type="submit">
                    Sign in</button>
                <!--
                <label class="checkbox pull-left">
                    <input type="checkbox" value="remember-me">
                    Remember me
                </label>
                -->
                </form>
            </div>
            <a href="{{ url_for('frontends.register') }}"
                class="text-center new-account">Create an account </a>
        </div>
    </div>
</div>
{% endblock %}

disxss/templates/macros.html
{% macro render_field(field) %}
  <div class="form_field">
  <!--{ field.label(class="label") }}-->
  {% if field.errors %}
    {% set css_class = 'has_error ' + kwargs.pop('class', '') %}
    {{ field(class=css_class, **kwargs) }}
    <div class="alert alert-dismissable alert-danger">{% for error in field.errors %}<li>{{ error|e }}</li>{% endfor %}</ul>
  {% else %}
    {{ field(**kwargs) }}
  {% endif %}
  </div>
{% endmacro %}